export const general = [
  {
    id: 1,
    generalId: '1',
    generalUniqueId: '11',
    general_vacuna: [
      'F_AFTOSA',
      'BRUCELOSIS',
      'VIRAL_REPRODUCTIVA',
      'DVB',
      'RABIA',
      'CARBUNCLO_SINTOMATICO',
      'CARBUNCLO_BACTERIANO',
      'SEXTUPLE',
      'IBR',
      'TUBERCULINA',
      'OTROS',
    ],
    general_raza: [
      'BRADFORD',
      'BRAHMAN',
      'NELOR',
      'SENEPOL',
      'GELVICH',
      'SANTA_GERTRUDIS',
      'SIMMENTALL',
      'CHAROLAIS',
      'LIMOUNSIN',
      'CRIOLLO',
      'OTROS',
    ],
    general_classificacion: [
      'DH',
      'DM',
      'TH',
      'TM',
      'TORO',
      'NOVILLO',
      'VACA',
      'VAQUILLA',
      'DESMAMANTE_MACHO',
      'DESMAMANTE_HEMBRA',
      'TERNERO',
      'TORETON',
      'VACA_PRENADA',
      'VACA_COM CRIA',
      'VACA_SECA',
      'VACA_CUT',
      'VACA_DONADORA',
      'VACA_RECEPTORA',
      'OTROS',
    ],
    general_dispositivo: ['RP', 'TN', 'TARJETA'],
    general_color: [
      'AMARILLO',
      'BARCINO',
      'BLANCO',
      'CHOVY',
      'NARANJA',
      'NEGRO',
      'OVERO',
      'PAMPA',
      'OSCO',
      'OTROS',
    ],
    general_categoria: [
      'D_H',
      'D_M',
      'T_H',
      'T_M',
      'TORO',
      'NOVILLO',
      'VACA',
      'VAQUILLA',
    ],
    general_modalidad: ['COMPRA', 'HOTELARIA', 'PARCERIA'],
    general_destino: [
      'Frigorifico Concepcion S.A.',
      'Frigorifico Frigomerc S.A.',
      'Frigorifico Neuland',
      'Frigorifico San Antonio S.A.',
      'Frigorifico Frigochorti',
      'Frigorifico FrigoChaco',
      'FRIGORIFICO GUARANI S.A.C.I.',
      'Frigorifico Mussa',
      'Frigorifico NORTE S.A.',
      'FRIGORIFICO BELEN',
      'FRIGORIFICO LOS LAZOS',
      'OTRO',
    ],
    general_permission: [
      'VPA',
      'FRIGORIFICO',
      'PROPIEDAD',
      'PRODUCTOR',
      'SENACSA',
      'ASSOCIACION',
      'PUESTOCONTROL',
      'GERENTE',
      '----',
      'ADMIN',
      'MANAGER',
      'CLIENT',
      'USER',
      'ROOT',
    ],
    general_tipo_salida: ['FAENA', 'MORTANDAD', 'TRANSFERENCIA'],
    general_controlador: ['1', '2', '3'],
    general_corral: ['1', '2', '3'],
    general_color_tag: ['AMARILLO', 'BLANCO', 'NARANJA'],
    general_sigla: ['ESDA-LAZO', 'NORD-LAZO', '3'],
    general_propietario: ['GANADERIA LOS LAZOS', '2', '3'],
    general_7: ['1', '2', '3'],
    general_8: ['1', '2', '3'],
    general_9: ['1', '2', '3'],
    general_10: ['1', '2', '3'],
    general_is_sync: true,
    dbversion: '1',
  },
];
